title: Parvesh Rawal blog
email: pr086832@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A simple blog site.
baseurl: ""
url: "https://Parveshiiii.github.io"

collections:
  blogs:
    output: true
    permalink: /blogs/:name/

markdown: kramdown
plugins:
  - jekyll-feed
